### ISSUE TITLE
Unexpected results with some municipality polygons

### ISSUE THREAD

**Issue by topive** [GispoCoding/NLSgpkgloader#11]
I've noticed that with some municipalities the plugin returns empty layers. For example, most recently the error occurred with Keuruu municipality. It seems to have something to do with invalid geometries because after fixing the polygon's geometries it worked fine.

**Comment by SannaJokela** [comment]
This is possibly same issue as described in #18 Might be about the data, we'll have to check this out. I'll close this as duplicate and refer here from the other issue.
