### ISSUE TITLE
Plugin uninstall doesn't work

### ISSUE THREAD

**Issue by joonaris** [GispoCoding/NLSgpkgloader#29]
When i try to uninstall plugin, it ends up to error message:
_"Lisäosan asennuksen poisto epäonnistui:Hakemiston poistaminen epäonnistui: C:/Users/Joona/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins/NLSgpkgloader-master Tarkista käyttöoikeutesi tai poista käsin"_

QGIS 3.22.7 LTR

**Comment by ismogis** [comment]
The bug doesn't appear in the versions 3.28 and newer.
