### ISSUE TITLE
QGIS 3.10 - python error

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/NLSgpkgloader#3]
Error noticed with QGIS 3.10, the plugin stopped downloading the data & caused apparently an error. At the same time 3.8. works fine.

**Comment by Joonalai** [comment]
I tested the download with QGIS 3.10 and it worked fine. Can you specify what layers and municipalities you were trying to download?

**Comment by SannaJokela** [comment]
Tested with Akaa, all the layers that are active, same thing happened again. Tried selecting a municipality, same thing. Window installation. QGIS stopped the process. Python error:  ConnectionResetError: [WinError 10054] Etäpalvelin sulki aiemmin luodun yhteyden

**Comment by Joonalai** [comment]
I just installed  QGIS 3.10.1-A Coruña to Windows 10 computer and tested the situation with Akaa, but I could not reproduce the error. The error message you had hints that another connection was tried to establish while the existing connection was still used.
