### ISSUE TITLE
Plugin doesn't open up with wrong API-key

### ISSUE THREAD

**Issue by annijus** [GispoCoding/NLSgpkgloader#31]
Hello!

I've tried to use NLS geopackage loader plugin but it doesn't work. I tried to open it but it just shows this error message:

WARNING   Traceback (most recent call last):
       File "C:\Users/Anni Jusslin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NLSgpkgloader-master\nls_geopackage_loader.py", line 232, in run
       self.product_types = self.downloadNLSProductTypes()
       File "C:\Users/Anni Jusslin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NLSgpkgloader-master\nls_geopackage_loader.py", line 571, in downloadNLSProductTypes
       e = xml.etree.ElementTree.fromstring(r.text)
       File "C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\xml\etree\ElementTree.py", line 1347, in XML
       parser.feed(text)
       xml.etree.ElementTree.ParseError: syntax error: line 8, column 0

What could be the issue in here? I tried to reinstall the plugin but that didn't helped.

**Comment by ismogis** [comment]
Probably, a wrong api key has been saved as an environment variable. The fix is either to create a new QGIS profile or remove the api key under the advanced settings (NLSgpkgloader -> userKey).

**Comment by SannaJokela** [comment]
This warning comes indeed when you have a wrong api-key. Tested with QGIS 3.34 and with new profile. I shall edit the issue name. In #25 an enhancement is suggested. Is there any way I could add the correct api-key manually some where? Only way to correct this issue now is you have to manually remove the plugin and reinstall (at least in windows).

**Comment by SannaJokela** [comment]
Duplicate with this issue with workaround #19. Closing this.
